### PR TITLE
Allow users to provide keys at runtime

### PR DESCRIPTION
**Pull request by citelao**
Hello! I want to set up a GitHub pipeline for this project, so that less-programmery folks can pick up and use libcutter.

To that end, I've implemented a quick-and-dirty way of **providing cutter keys at runtime**. Today, the build will warn if no keys are compiled in; with this change,`draw_gcode` will expect keys to be provided as arguments.

**Providing this as a slightly-early PR for feedback**. I think the arg parsing is very dirty; I'd rather parse a JSON file, but that's hard to do cross-platform. I'm open to reworking this code however makes sense.

## What changed?

* Add max-tested CMake version to avoid some warnings.
* Opt into C++17
* Update `keys.h` to no longer warn.
* Make `draw_gcode` argument parsing more robust
* ~~Add new `--mk`, `--lk`, and `--ck` flags to `draw_gcode`---they are required when no compile-time keys are present.~~
* Introduce a `KeyConfigParser` that can parse a specially-formatted configuration file.
* Consume that parser in `draw_gcode`, `draw_svg`, `interpreter`, and `test_speed`
* Document this behavior in README.

## How tested?

* [x] Drawing arbitrary GCode moves the machine & cuts when keys are provided at runtime
* [x] Drawing arbitrary SVG moves the machine & cuts when keys are provided at runtime
* [x] Running the interpreter moves the machine & cuts when keys are provided at runtime
* [x] Running `test_speed` moves the machine & cuts when keys are provided at runtime
* [ ] Drawing arbitrary GCode still moves the machine & cuts when keys are provided at compile-time
* [ ] Drawing arbitrary SVG still moves the machine & cuts when keys are provided at compile-time
* [ ] Running the interpreter still moves the machine & cuts when keys are provided at compile-time
* [ ] Running `test_speed` still moves the machine & cuts when keys are provided at compile-time

## TODO

* [x] Support these flags in `draw_svg`
* [ ] Hide these flags when compile-time keys are provided.

### CODE REVIEW

**Comment by rsaxvc** [comment]
Hi,

> I want to set up a GitHub pipeline for this project, so that less-programmery folks can pick up and use libcutter.

I think this is an excellent idea.

> Drawing arbitrary GCode moves the machine & cuts when keys are provided at runtime

Neat! Can I ask, which machine(s) are you using? I don't have one currently.

>I'd rather parse a JSON file, but that's hard to do cross-platform

Dunno about JSON, but some sort of user controlled file (~/.libcutter/machine-specific-file?) might make sense for key storage. Then we might remove keys.h entirely. Also, we suspect Provocraft uses at least two different key sets, for different machines, and may have done so with a firmware upgrade at some point as well.

**Comment by citelao** [comment]
@rsaxvc I'm using an old Cricut Expression that we have lying around.

In terms of command-line parameters vs parsing, I'm of two minds:

1. Passing all of the keys as parameters is not pretty at all `./foo --mk key key key key --ck key key key key --lk key key key key` and it doesn't scale to other operations.
2. On the other hand:
    * Parsing a file seems difficult and error-prone; if this were JS or Python or whatever we could do json_decode and be done with it. I guess we could try to make a super simple format (`KEY0: foo\nKEY1: bar\n`)---and I guess we're basically parsing the command line anyway at this point with my changes.
    * It might be a bit daunting to ask users to provide a file *in addition* to downloading this tool; I know we're already limiting the audience since this is a command-line tool, but I worry strongly about ease-of-use (especially given the recent Cricut kerfuffle about printing custom designs). At the very least we should support `-f myfilehere.ini`.
    * Are there cross-platform concerns? I've not used MSYS2/MinGW before so I guess `fopen` will Just Work on Windows in those environments.

We could split the difference and let users pass keys in as parameters OR by file...

---

As an aside, have y'all had reliability issues with sending commands? I've found that libcutter sometimes stalls when sending the first messages. I ask because I've basically written a clone in this in Node.JS & TypeScript, but I've not shared it because I get reliability issues occasionally when sending commands.

(If there's a lot to this last point, say the word and we can put it in a separate issue for discussion).

Thanks for your help!

**Comment by rsaxvc** [comment]
Please consider this 10+ year old memories and conjecture about serial port
reliability. I'm on lunch break so I don't have the code with me.

First you need the port in raw/uncooked/binary mode for whatever OS you
have.

I think that the baud rate between the USB converter and the
microcontroller is faster than the microcontroller can sustain under all
conditions.

I think there is some manual delay somewhere in libcutter before the data
hits the serial port driver to accommodate this.

I don't recall if this is an issue for each byte or for each command, there
might be a different delay for each.

You may also need to wait between commands? Hopefully there's a status
command to check if it's still moving? Sorry, it's been a while.

If you do fiddle with the delays, be advised that the OS kernel scheduling
will fiddle with it further for you - trying to sleep for 1ms used to
/usually would suspend your thread much longer than that on Windows, Mac
and Linux were somewhat better. Anyways - if you want to fiddle with the
delays you need to measure the timing between start bits coming out of the
USB converter in the device on their way to the microcontroller.

The timing delays currently should provide the minimum but may be
inefficient on some platforms, but it shouldn't be too bad. Still faster
than hand cutting motorcycle gaskets in any case.

If you don't have the appropriate delay in your implementation, it's also
possible the OS driver might help you if you only send a byte at a time,
because the USB1.1 packet/polling rate is 1KHz, but if the OS transmit
queue gets too long, the OS may combine multiple bytes into a single USB
packet, causing a UART overflow when the micro doesn't process it fast
enough. This can give intermittent behavior on different platforms, as well
as if you combine writes.

**Comment by citelao** [comment]
Thanks for the info, @rsaxvc! I guess I’ll just have to do more investigating. I know the commands seem to all send a 5 byte response (0x04 + something that looks encrypted). Maybe there’s helpful info there...

For this PR, though, what are your thoughts on file versus parameters?

It might be practical to support both... for the experimental use case (“do these keys even work?”) parameters seem a lot better, but for the everyday use case a file would be nice (though, tbh I expect the true use case would be via a GUI that plugs ‘em in for you). 

I’m open to any design here—just want to do the right thing. My code is spaghetti and needs cleanup in any case.

**Comment by rsaxvc** [comment]
I'm thinking a simple key-value file format should work well. Maybe INI?
Parser should probably be in it's own file, separate from the driver(I
think it supports setting keys at runtime already?), and sharable between
applications.

Also, could you please note the firmware version your unit currently has?
Sometimes people come asking which models and firmware versions are
supported.

**Comment by citelao** [comment]
> I'm thinking a simple key-value file format should work well. Maybe INI? Parser should probably be in it's own file, separate from the driver(I think it supports setting keys at runtime already?), and sharable between applications.

I agree it should be a separate file. I'll take a look.

> Also, could you please note the firmware version your unit currently has?
Sometimes people come asking which models and firmware versions are
supported.

I believe my firmware version is v2.31. I don't have the actual bytes received handy, though.

**Comment by citelao** [comment]
I've given it a shot using a config file. Unfortunately, I'm missing `svg.h` and I don't have SDL, so I'll have to get that working to update some of the other files.

**Comment by rsaxvc** [comment]
There's a copy of libsvg in the deps folder.

**Comment by citelao** [comment]
All the programs that require keys should be updated now. I have yet to test the behavior when I provide compile-time keys.

Note that I found the programs to be quite unreliable on my M1 MacBook Pro. But I don't think that's related to my changes.

**Comment by rsaxvc** [comment]
I'm sorry I haven't gotten back to this sooner. I have merged a couple commits, but need to review more.

Could you please squash the relevant commits down? I think there are some that fix some in the same series.

Also, anything that can be separated out should be split to another pull request(I think adding vscode stuff was there, but we should consider adding it separately from this patch series).

Similarly, I might be able to merge the fix-mac-build commit separately.

What do you think about switching from KeySpaceValue to KeyEqualsValue, to be more INI style?

**Comment by rsaxvc** [comment]
I wonder if we even need to support compile time keys?

**Comment by citelao** [comment]
> I'm sorry I haven't gotten back to this sooner. I have merged a couple commits, but need to review more.
> 
> Could you please squash the relevant commits down? I think there are some that fix some in the same series.

I'm not averse to it; I typically squash them via the UI when merging commits (you can merge squashed).

> Also, anything that can be separated out should be split to another pull request(I think adding vscode stuff was there, but we should consider adding it separately from this patch series).
> 
> Similarly, I might be able to merge the fix-mac-build commit separately.

I'm happy to do so, I avoided that since they all help me work on my this PR 😄.

> What do you think about switching from KeySpaceValue to KeyEqualsValue, to be more INI style?

* Upside: more INI like
* Downside: I can't parse it in 1 line. I'd have to split the string based on equality; just a little more code on my end.

> I wonder if we even need to support compile time keys?

🤷‍♀️ the code works as-is; I'm happy to remove `keys.h` entirely. I didn't want to annoy anyone who might prefer the compile-time keys, though I doubt that person exists.

**Comment by rsaxvc** [comment]
Removing keys.h entirely seems worth it to me in terms of test effort and
getting everyone on a single codebase.

**Comment by rsaxvc** [comment]
I will hopefully merge this tonight with a few additions.

**Comment by citelao** [comment]
Oh ok! I was going to take a look at removing `keys.h` and separating stuff into a few PRs. Cool stuff!

**Comment by rsaxvc** [comment]
I'm going to be in the land of 2G this week, and busy the next two, so I wanted to get something in soon.

**Pull request merged**
