### PR TITLE
Ported to libSDL2

### PR DESCRIPTION
**Pull request by smonson78**
Hello!

I have ported the simulation utility to SDL2. I'm not sure if anyone else is interested in this patch, but in case you are, here it is :)

I have not been able to get the CMake config to work so someone else would have to test that it builds OK.

### CODE REVIEW

**Comment by rsaxvc** [comment]
Hi!

Just curious, how were you building it? The win32 script?

**Comment by rsaxvc** [comment]
I get some flickering when I run `./build/util/draw_svg_cv util/svg_tests/555_Astable_Diagram.svg 1` - I don't think it did that before.

**Comment by smonson78** [comment]
Hi @rsaxvc,

> Just curious, how were you building it? The win32 script?

I have written a Makefile for it (apart from the SWIG interface).

> I get some flickering when I run ./build/util/draw_svg_cv util/svg_tests/555_Astable_Diagram.svg 1 - I don't think it did that before.

Hmm, sorry about that, I didn't experience that behaviour on my machine (Ubuntu 20.10, nvidia drivers). I'll take another look tomorrow evening and see if I can work it out. Thank you for considering this PR!

**Comment by rsaxvc** [comment]
It looks like my laptop GPU? LCD? flex? is going out, so that may be on my end, but i only noticed the flicker on the lines of the PCB demo. I'll check it on another machine but the patch otherwise looks fine.

**Comment by rsaxvc** [comment]
I also updated some of the CMake files last night. It built with CMake on Debian 10.

**Comment by smonson78** [comment]
I've rebased this PR against master and also added another commit to add proper init/quit routines that I missed the first time around. I've also changed it over to request software rendering. When you have time, could you check and see if that improves the flickering?

**Comment by rsaxvc** [comment]
I have squashed and merged it.

**Comment by smonson78** [comment]
Thank you.

**Pull request closed without merging**
